swagger: "2.0"
info:
  description: "This is API Document of Starl-Backend"
  version: "1.0.0"
  title: "Starl-Backend API Document"
  contact:
    email: "developer.starl.co.jp@gmail.com"
host: "hostName"
basePath: "/basePath"

tags:
  - name: "User"
    description: "Access to User Information"
  - name: "Sign"
    description: "Sign up, sign in, and sign out"

schemes:
  - "https"

securityDefinitions:
  cookieAuth:
    type: "apiKey"
    in: "header"
    name: "sessionId"

paths:
  # -------------------- User ----------------------
  /v1/user:
    get:
      tags:
        - "User"
      summary: "Get all users"
      description: ""
      operationId: ""
      security:
        - cookieAuth: []
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                example: 1
              username:
                type: "string"
                example: "username"
              code:
                type: "integer"
                example: 12345678
              amount:
                type: "integer"
                example: 12345
        "401":
          description: "Unauthorized"
        "404":
          description: "User Not Found"
    post:
      tags:
        - "User"
      summary: "Create user"
      description: ""
      operationId: ""
      security:
        - cookieAuth: []
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          description: "Latest user object"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
                example: "username"
              password:
                type: "string"
                example: "p@ssw0rd"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                example: 1
              username:
                type: "string"
                example: "username"
              code:
                type: "integer"
                example: 12345678
              amount:
                type: "integer"
                example: 0
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
    put:
      tags:
        - "User"
      summary: "Update attributes of user resource"
      description: ""
      operationId: ""
      security:
        - cookieAuth: []
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          description: "Latest user object"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
                example: "newusername"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                example: 1
              username:
                type: "string"
                example: "newusername"
              code:
                type: "integer"
                example: 12345678
              amount:
                type: "integer"
                example: 12345
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "404":
          description: "User Not Found"
    delete:
      tags:
        - "User"
      summary: "Delete user"
      description: ""
      operationId: ""
      security:
        - cookieAuth: []
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          description: "password"
          required: true
          schema:
            type: "object"
            properties:
              password:
                type: "string"
                example: "password"
      responses:
        "200":
          description: "Successful Operation"
        "401":
          description: "Unauthorized"
